# Generated by Django 4.1.7 on 2023-03-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Body', models.TextField()),
                ('Category', models.CharField(max_length=200)),
                ('Published', models.DateTimeField(auto_now_add=True)),
                ('Update', models.DateTimeField(auto_now=True)),
                ('Slug', models.SlugField(blank=True, editable=False)),
            ],
        ),
    ]
